### ISSUE TITLE
Planets and Star with Oblate shape 

### ISSUE THREAD

**Issue by chelseah** [CadenArmstrong/simuTrans#3]
Implement the part so that the shape of planet and star can have an oblate shape.

**Comment by CadenArmstrong** [comment]
Implemented.
Rp/Rs is currently using equitorial / equitorial.
f = equitorial - polar/equitorial
Star equitorial is set to 1.
Limb darkening is taken such that radius = radius_sphere / radius_oblate.

**Comment by chelseah** [comment]
Thanks!
I'll have a look before Tuesday, and we can add in the simple GD part on
Tuesday if everything works out.

Best,
Chelsea

**Comment by CadenArmstrong** [comment]
Need to use Barnes (2009) model for 3-D oblate shape.

**Comment by chelseah** [comment]
see issue #4 for the remaining problems
